
Loading components for TIF035

Traceback (most recent call last):
  File "./task2.py", line 50, in <module>
    main()
  File "./task2.py", line 46, in main
    result = str(params[0])+'\t'+str(params[1])+'\t'+str(params[2])+'\t'+str(params[3])
IndexError: tuple index out of range
GPAW CLEANUP (node 7): <type 'exceptions.IndexError'> occurred.  Calling MPI_Abort!
Traceback (most recent call last):
  File "./task2.py", line 50, in <module>
    main()
  File "./task2.py", line 46, in main
    result = str(params[0])+'\t'+str(params[1])+'\t'+str(params[2])+'\t'+str(params[3])
IndexError: tuple index out of range
GPAW CLEANUP (node 5): <type 'exceptions.IndexError'> occurred.  Calling MPI_Abort!
Traceback (most recent call last):
  File "./task2.py", line 50, in <module>
    main()
  File "./task2.py", line 46, in main
    result = str(params[0])+'\t'+str(params[1])+'\t'+str(params[2])+'\t'+str(params[3])
IndexError: tuple index out of range
GPAW CLEANUP (node 4): <type 'exceptions.IndexError'> occurred.  Calling MPI_Abort!
Traceback (most recent call last):
  File "./task2.py", line 50, in <module>
    main()
  File "./task2.py", line 46, in main
    result = str(params[0])+'\t'+str(params[1])+'\t'+str(params[2])+'\t'+str(params[3])
IndexError: tuple index out of range
GPAW CLEANUP (node 3): <type 'exceptions.IndexError'> occurred.  Calling MPI_Abort!
Traceback (most recent call last):
  File "./task2.py", line 50, in <module>
    main()
  File "./task2.py", line 46, in main
    result = str(params[0])+'\t'+str(params[1])+'\t'+str(params[2])+'\t'+str(params[3])
IndexError: tuple index out of range
GPAW CLEANUP (node 1): <type 'exceptions.IndexError'> occurred.  Calling MPI_Abort!
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 7 in communicator MPI_COMM_WORLD 
with errorcode 42.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun has exited due to process rank 7 with PID 16989 on
node beda61-3.nfs.private exiting without calling "finalize". This may
have caused other processes in the application to be
terminated by signals sent by mpirun (as reported here).
--------------------------------------------------------------------------
